### ISSUE TITLE
Error when switching from config to design [Crash]

### ISSUE THREAD

**Issue by ghost** [X39/ArmA-UI-Editor#11]
# Steps to reproduce
1. Start app
2. Go to config (do not edit anything)
3. Go back to design
# Issues
- While step 3: Sometimes (Only one time for me), application crashs
# Additional Notes
- Windows exception error log :

[ErrorLog.txt](https://github.com/X39/ArmA-UI-Editor/files/272266/ErrorLog.txt)

**Comment by X39** [comment]
Sadly log does not says anything ...
next release (alpha) will contain a fully refractured and reviewed system in this regards that should fix it ... in case it appears again, attach the crash.txt (its created automatically) and reopen :)

thanks for the report ... but sorry for not being able to find anything
