### ISSUE TITLE
Positions and Sizes are wrong

### ISSUE THREAD

**Issue by kayler-renslow** [X39/ArmA-UI-Editor#12]
Positions and sizes (w,h) are wrong. They are supposed to be percentage decimals based upon the 4:3 absolute box.
[Some relevant documentation](https://community.bistudio.com/wiki/SafeZone)

If x,y = 0 and w,h =1, a box will fill the center of the screen according to where the absolute region box is. Example image attached.
![positioning](https://cloud.githubusercontent.com/assets/16510625/15700246/74226804-2798-11e6-80b8-1b0f8126abde.jpg)

**Comment by X39** [comment]
apparently a known issue ... current sizing is not correct and will be fixed as soon as i find the time to get it right :3

thanks for reporting still, so it wont be forgotten
