### ISSUE TITLE
[Suggestion]Ability to use preprocessor 

### ISSUE THREAD

**Issue by darderik** [X39/ArmA-UI-Editor#14]
It would be nice to allow to include a file which defines various classes. I'm using a mission built using a common.hpp(example [here](https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/dialog/common.hpp)),which denies me to edit the dialogs integrated in the mission by directly importing them in the editor.

**Comment by X39** [comment]
At current technology standpoint, the config is regenerated on every change using the graphical UI --> defines would get lost

so just to get your request clear: do you just want the preprocessor to be used for a one-time import? or do you want the tool to maintain the preprocessor stuff?

**Comment by darderik** [comment]
Uhm.. choose the easier thing for you
It would be nice to mantain preprocessor stuff,but it could result difficult. 
So in my opinion,almost same thing.

**Comment by X39** [comment]
Check
for now, goal will then be to just parse the preprocessor

sooner or latter the entire config parsing will get rewritten anyway to support partial changes so that your custom styling will be maintained

**Comment by X39** [comment]
implemented in https://github.com/X39/ArmA-UI-Editor/commit/27c72f998ec84dc6657ce1c79c7c9d1ee1db29ad

currently translates the document fully, inner document workflow does not allows for preprocessor

**Comment by darderik** [comment]
Where should the class be defined?

**Comment by X39** [comment]
please be more specific @DardoTheMaster about what you mean

**Comment by darderik** [comment]
I can not found the button or menu where I should put the preprocessor instructions (?),am I completely dumb?

**Comment by X39** [comment]
it will only work on "Open File" with current implementation

**Comment by X39** [comment]
just got a bug report of yours (at least i think it is of yours)
fix already done however, your config is not suited for the tool

the actual UI displayed in the end has to be placed at the very end and needs to contain a controls class
there could be further crashes ... all of em will be fixed as soon as i receive em :)

greets
X39

**Comment by darderik** [comment]
Oh,sorry for the useless report. I thought that before opening the "macroed" dialog I had to load a config. 
Will there be in the future a similiar feature,allowing to define preprocessor instructions using a separated .hpp?

**Comment by X39** [comment]
it is currently not planned (as that is not the intension with the UI editor ^^ what you want to archive is actually made possible using the AddIns as i cannot display 100% custom controls sadly ... so at least they have to have normal ArmA parents to work proper or you create the AddIns yourself)
