### ISSUE TITLE
Editor crashes by Changing Text

### ISSUE THREAD

**Issue by F4BI** [X39/ArmA-UI-Editor#16]
# Steps to reproduce
1. Edit Text of RscText by Property
2. Press Enter to apply changes
# Issues
- While step 2: Editor crashes
# Expected
- While step 2: Text should be applyed

**Comment by X39** [comment]
any chance you could add the crash.txt to this? (if auto-reporting is enabled, #15 could be your crash)

should be located in the application dir

**Comment by F4BI** [comment]
I had diabled auto-reporting but it was enabled by itself :/
Sry but can´t find crash.txt.

**Comment by X39** [comment]
weird ... seems like there is a bug then too
anyway, will be fixed in a hotfix release tonight

**Comment by X39** [comment]
fixed in https://github.com/X39/ArmA-UI-Editor/commit/19cc58496906dec65b76a45a834b90bddf31a546
