### ISSUE TITLE
Add alignment options

### ISSUE THREAD

**Issue by Krzmbrzl** [X39/ArmA-UI-Editor#30]
It would be nice to see an option for each UI element that allows the user to align it (left, right, up, down, vertical center, horizontal center)

**Comment by Krzmbrzl** [comment]
And as a further step it would be cool to have relative alignment options to other UI elemnts as well :)

**Comment by X39** [comment]
not sure what you mean with this request

please crosscheck if duplicate or go more in detail: https://github.com/X39/ArmA-UI-Editor/issues/21

**Comment by Krzmbrzl** [comment]
No what I mean is the pure alignment... Not snapping.

An example would be:
I have a button I want to put in the center of my screen. Currently I have to guess where the center is and move it there by hand.
With such alignment options I would simply select the control and set it to align to the vertical and horizontal center and voilá it is in the exact center of the screen.

I mean the same functionality as you find them in many image manipulation programs such as Inkscape:
See [here](https://www.youtube.com/watch?v=QaxSKwKJbNQ) (Warning: terrible voice), [here](http://tavmjong.free.fr/INKSCAPE/MANUAL/html/Align.html) and [here](http://clownfishcafe.blogspot.de/2014/03/align-and-distribute-in-inkscape.html)

The relative alignment would be the same only that it doesn't take the complete screen as an reference/anchor but another control

**Comment by X39** [comment]
at least the second thing is not possible to archive unless control groups are introduced (which also will be at some point, but that will be at a very late state of developement)

for the first thing ... well ... will have low priority
you also could just calculate the required width/x & height/y ratio
