### ISSUE TITLE
Add fullscreen mode

### ISSUE THREAD

**Issue by Krzmbrzl** [X39/ArmA-UI-Editor#32]
Would be nice to be able to edit the dialog in fullscreen mode (The actual dialog window taking up the complete screen instead of just a part of it because all the option panes are taking up the space...)

**Comment by X39** [comment]
Whats currently planned on this:
it is supposed to be possible to drag the different panes out in new windows (and in those windows rearange the different panes again)
which would be essentially what you want if i got this ticket right

**Comment by Krzmbrzl** [comment]
So the window would hover above the actual dialog-window and are not taking screen space by themselves (of course they do but currently they resize the main window when being shown)?
The yep that's what I meant.

For this functionality it would be nice to have some kind of hotkey that hides/shows all currently open "hover-windows" so that one can toggle them on and off for reviewing the current state of the UI without having to close and reopen all the windows manually

**Comment by X39** [comment]
currently, they do not resize the main window
the actual main window is the entire window

they change the space available for the editing snap
hiding/showing all snaps but editing snap is currently not planned (but maybe it will get possible at some point via some specific addin option ... we will see ... would be quite hard to implement)

those will be pullable out of the window to create a new one (see visual studio eg. as reference for the targeted behaviour) also, per default the tabs will at some point not pin automatically on click (thats just current behaviour as that was more simple to do for now)

**Comment by Krzmbrzl** [comment]
Okay... Yep that will do what I intended with this ticket :D
