### ISSUE TITLE
Property changes should get overtaken immediately

### ISSUE THREAD

**Issue by Krzmbrzl** [X39/ArmA-UI-Editor#36]
Currently one has to hit enter in order to make the editor overtake the property from the currently selected property-field but it should do this while typing/changing the field or, if that's a problem because of error-spammimg in case of incomplete properties, it should overtake the field's value on focus lost of the field.

**Comment by X39** [comment]
Was done for simplicity
will be fixed with config parser recreation (should create an issue for that to crosslink ...)

**Comment by X39** [comment]
Fixed in Alpha Release 8
