### ISSUE TITLE
New controls should have a width and height from beginning on

### ISSUE THREAD

**Issue by Krzmbrzl** [X39/ArmA-UI-Editor#37]
# Steps to reproduce
1. Place new control
2. Look into properties
# Issues
- While step 2: Width and height are not set
  Expected
  ========
- While step 2: They should be set in case the user is satisfied with default width/height

**Comment by X39** [comment]
How would you imagine theese controls to be set with their initial width/height?

at current state of the art, the controls contain their parents width/height (which would lead to different results in-game due to a few modifications here, just like with the x/y stuff)

**Comment by Krzmbrzl** [comment]
So the width/heigth is not yet functional?

I thought they just get assigned the width and height of the little box that represents the control (which obviously has a certain width and height already), because I noticed that the control gets these values assigned as soon as I scale it. Therefore I thought the initial values are simply forgotten to set...

**Comment by X39** [comment]
Initial values are inheritanced by the parent classes
all parent classes contain default x/y/w/h values

**Comment by Krzmbrzl** [comment]
Okay... But are these the values the element in the editor mirror with their initial size? So if I place a control and don't resize it does it appear in the same dimension inGame as in the editor?

If so then this ticket can be closed

**Comment by X39** [comment]
not at current state of the art
if you do not resize the control, it will most likely appear with 0 width and 0 height

**Comment by Krzmbrzl** [comment]
That's what I suspected. It came into my mind because I had this exact case and I think users might be confused when controls simply dissappear in game ^^

**Comment by X39** [comment]
fixed in https://github.com/X39/ArmA-UI-Editor/commit/04d49d67e4d89ea0a1f6cbd8c03b5b434c0ded5e
