### ISSUE TITLE
Add render/Screenshot option 

### ISSUE THREAD

**Issue by Krzmbrzl** [X39/ArmA-UI-Editor#39]
This just came into my mind. 
It would be handy if one could render the GUI (so the content of the window displaying how the UI will look in game) as a png/jpg so that you could show it to someone else as some kind of mockup... 

I know that this will not have priority but in my opinion it would be a nice gimmick for the future.

**Comment by X39** [comment]
we will see ...

https://stackoverflow.com/questions/21411878/saving-a-canvas-to-png-c-sharp-wpf
