### ISSUE TITLE
Dialogs must have an idd

### ISSUE THREAD

**Issue by Krzmbrzl** [X39/ArmA-UI-Editor#42]
# Steps to reproduce
1. Create new dialog
2. Look into the dialog properties
# Issues
- While step 2: No idd is set
# Expected
- While step 2: A default one should be set (-1) as the game does require the idd to be set

**Comment by X39** [comment]
fixed in https://github.com/X39/ArmA-UI-Editor/commit/33ebb839a982c0bf3dc99c81f27766e760c55629
