### ISSUE TITLE
Option to create the UI via SQF (ctrlCreate)

### ISSUE THREAD

**Issue by Krzmbrzl** [X39/ArmA-UI-Editor#44]
Another handy feature would be to be able to let the tool generate a little SQF file that creates the respective GUI via ctrlCreate.
Of course that is only possible if the used base-classes are the same as available for usage with ctrlCreate and the respective display has to be given by the user as well.
Best way in my opinion would be to create a controlsGroup and put the dialog in there.

But why would you need this?
- No need for bunches of config-files
- No need for base-classes in configs
- In some situations this is the only way to go (e.g. render the UI over the default map if you still want to be able to use the map)

**Comment by X39** [comment]
impossible in too many ways

ctrlCreate is way to limited in regards of styling which would mean that a "limited" mode would have to be introduced
that limited mode would require pretty much every AddIn to be "introduced" twice

rejected
