### ISSUE TITLE
Still being developed/updated

### ISSUE THREAD

**Issue by trdwll** [X39/ArmA-UI-Editor#51]
Is this going to be updated and or is it still in development?

**Comment by X39** [comment]
It is slowly getting replaced by https://github.com/X39/ArmA.Studio which started as MVVM rewrite of this tool and ended up becomming a full ArmA IDE including a debugger

though ... the UI editing will not be included in initial release of that tool

the ArmA-UI-Editor tool itself might receive some patches but in wont receive any more major updates.

kindly regards
X39

**Comment by trdwll** [comment]
Thanks for the update. When I get some free time I may submit a PR.

**Comment by X39** [comment]
feel free to do so
in case you want access to some of the crash logs reported to my webpage, feel free to ask

gonna close this ticket now :)
feel free to reopen in case more questions come up
